#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR
java -jar tracey-cli-rabbitmq.jar say -f scc.json -c default.cfg
sleep 5
java -jar tracey-cli-rabbitmq.jar say -f scs.json -c default.cfg
